//
//  CategoriesPresenter.swift
//  Test.GuiaBolso
//
//  Created by Leandro Romano on 27/06/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoriesPresentationLogic {
    func presentSomething(response: Categories.Something.Response)
}

class CategoriesPresenter: CategoriesPresentationLogic {

    weak var viewController: CategoriesDisplayLogic?

    // MARK: Do something

    func presentSomething(response: Categories.Something.Response) {
        let viewModel = Categories.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
}
