//
//  CategoriesInteractor.swift
//  Test.GuiaBolso
//
//  Created by Leandro Romano on 27/06/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoriesBusinessLogic {
    func doSomething(request: Categories.Something.Request)
}

protocol CategoriesDataStore {
    //var name: String { get set }
}

class CategoriesInteractor: CategoriesBusinessLogic, CategoriesDataStore {

    var presenter: CategoriesPresentationLogic?
    var worker: CategoriesWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: Categories.Something.Request) {
        worker = CategoriesWorker()
        worker?.doSomeWork()
        
        let response = Categories.Something.Response()
        presenter?.presentSomething(response: response)
    }

}
