//
//  CategoriesWorker.swift
//  Test.GuiaBolso
//
//  Created by Leandro Romano on 27/06/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import PromiseKit

class CategoriesWorker {

    let networkProvider = NetworkProvider()
    
    func getCategories() -> Promise<[String]> {
        return networkProvider.request(.getCategories())
    }

}
