//
//  CategoriesPresenter.swift
//  Test.GuiaBolso
//
//  Created by Leandro Romano on 27/06/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CategoriesPresentationLogic {
    func presentLoadingState()
    func presentDynamicData()
    func presentError(_ error: Error)
    func presentRandomJoke()
}

class CategoriesPresenter: CategoriesPresentationLogic {

    weak var viewController: CategoriesDisplayLogic?

    func presentLoadingState() {
        viewController?.displayLoadingState()
    }
    
    func presentDynamicData() {
        viewController?.displayDynamicData()
    }
    
    func presentError(_ error: Error) {
        viewController?.displayResponseError(message: error.localizedDescription)
    }
    
    func presentRandomJoke() {
        viewController?.displayRandomJoke()
    }
    
}
