//
//  CategoriesRouter.swift
//  Test.GuiaBolso
//
//  Created by Leandro Romano on 27/06/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CategoriesRoutingLogic {
    func routeToJoke()
}

protocol CategoriesDataPassing {
    var dataStore: CategoriesDataStore? { get }
}

class CategoriesRouter: NSObject, CategoriesRoutingLogic, CategoriesDataPassing {

    weak var viewController: CategoriesViewController?
    var dataStore: CategoriesDataStore?
    
    func routeToJoke() {
        let jokeViewController = JokeViewController(nibName: R.nib.jokeViewController.name, bundle: nil)
        guard let dataStore = dataStore, let jokeRouter = jokeViewController.router, var jokeDataStore = jokeRouter.dataStore else { return }
        passDataToJoke(source: dataStore, destination: &jokeDataStore)
        navigateToJoke(source: viewController, destination: jokeViewController)
    }
    
    func navigateToJoke(source: CategoriesViewController?, destination: JokeViewController) {
        source?.navigationController?.pushViewController(destination, animated: true)
    }
    
    func passDataToJoke(source: CategoriesDataStore, destination: inout JokeDataStore) {
        destination.category = source.category
    }

}
