//
//  JokeWorker.swift
//  Test.GuiaBolso
//
//  Created by Leandro Romano on 28/06/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import PromiseKit

class JokeWorker {

    let networkProvider = NetworkProvider()
    
    func getRandomJokeFor(category jokeCategory: String) -> Promise<Joke.Response> {
        return networkProvider.request(.getRandomJokeFor(category: jokeCategory))
    }

}
