//
//  JokeModels.swift
//  Test.GuiaBolso
//
//  Created by Leandro Romano on 28/06/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum Joke {
  
    struct Response: Codable {
        
        let id: String
        let phrase: String
        let jokeUrl: String
        let iconImageUrl: String
        let createdAt: String
        let updatedAt: String
        
        enum CodingKeys: String, CodingKey {
            case id
            case phrase = "value"
            case jokeUrl = "url"
            case iconImageUrl = "icon_url"
            case createdAt = "created_at"
            case updatedAt = "updated_at"
        }
        
    }
    
    struct ViewModel {
        
        let phrase: String
        let iconImageUrl: String
        
        init(joke: Joke.Response) {
            self.phrase = joke.phrase
            self.iconImageUrl = joke.iconImageUrl
        }
        
    }

}
