//
//  JokeRouter.swift
//  Test.GuiaBolso
//
//  Created by Leandro Romano on 28/06/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol JokeRoutingLogic { }

protocol JokeDataPassing {
    var dataStore: JokeDataStore? { get }
}

class JokeRouter: NSObject, JokeRoutingLogic, JokeDataPassing {

    weak var viewController: JokeViewController?
    var dataStore: JokeDataStore?

}
